stages:
  - golang_build
  - ftp_upload

variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  BUILD_USER: $GITLAB_USER_LOGIN
  COMMITE_TITLE: $CI_COMMIT_TITLE

golang_build:
  stage: golang_build
  script:
    - export GOPROXY=https://goproxy.cn
    - go mod tidy
    - go build
    - CGO_ENABLED=0 go build -o test_server benchmark/server/main.go
    - CGO_ENABLED=0 go build -o test_client benchmark/client/main.go
    - CGO_ENABLED=0 go build -o test_ping benchmark/ping/main.go
  artifacts:
    expire_in: 7 day
    paths:
      - hmq
      - test_server
      - test_client
      - test_ping