stages:
  - golang_build

variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  BUILD_USER: $GITLAB_USER_LOGIN
  COMMITE_TITLE: $CI_COMMIT_TITLE

golang_build:
  stage: golang_build
  script:
    - export GOPROXY=https://goproxy.cn
    - go mod tidy
    - go build
  artifacts:
    expire_in: 7 day
    paths:
      - rocketmqtt
